###
#  Create user
POST http://localhost:3001/user HTTP/1.1
Content-Type:  application/json

{
	"name": "Teste",
	"email": "teste@gmail.com",
	"password": "123",
	"googleId": "1",
	"dateOfBirth": "2003-04-16",
	"height": "171",
	"weight": "70",
	"admin": "true"
}

### 
# See all users
GET http://localhost:3001/users HTTP/1.1


### 

# Get a specific user
GET http://localhost:3001/user/63e3b266e5f6db1e92b8fef8 HTTP/1.1

### 

# Update a user
POST http://localhost:3001/user/63e3b266e5f6db1e92b8fef8 HTTP/1.1
Content-Type:  application/json

{
	"name": "Stefan Taiguara",
	"email": "stefantleal14@gmail.com",
	"password": "123",
	"googleId": "2",
	"dateOfBirth": "1998-08-24",
	"height": "171",
	"weight": "53"
}

### 
## Delete a user
DELETE http://localhost:3001/user/63e3e3d130b0673af6bf91cc HTTP/1.1

###
# Add a diet to a user
POST http://localhost:3001/user/63e3e40130b0673af6bf91d4/diet HTTP/1.1
Content-Type:  application/json

{
	"breakfast": [{
		"title": "Omelete",
		"subtitle": "Omelete com queijo",
	}],
	"postWorkout": [{
		"title": "Batata doce",
		"subtitle": "Batata doce com frango"
	}],
	"morningSnack": [{
		"title": "Pão de queijo",
		"subtitle": "Pão de queijo com queijo"
	}],
	"lunch": [{
		"title": "Arroz",
		"subtitle": "Arroz com feijão"
	}],
	"afternoonSnack": [{
		"title": "Pão de queijo",
		"subtitle": "Pão de queijo com queijo"
	}],
	"dinner": [{
		"title": "Arroz",
		"subtitle": "Arroz com feijão"
	}],
	"nightSnack": [{
		"title": "Pão de queijo",
		"subtitle": "Pão de queijo com queijo"
	}]
}
